### ISSUE TITLE
Page isn't redirecting properly

### ISSUE THREAD

**Issue by mtasuandi** [shin1x1/laravel-force-secure-url-scheme#2]
Hi,

Thanks for the laravel package, unfortunately I had an issue while integrating this package with my project.

The project URL is http://www.paidup.io. I use Heroku to deploy the application and my Laravel version is 5.1.17.

This is my htaccess:

```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On
    # Redirect Trailing Slashes If Not A Folder...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```

This (http://www.paidup.io) url works before using this package, our plan is to use HTTPS connection instead of HTTP. Previously I've tried several way by updating the .htaccess but still didn't work.

As you can see, if you go to http://www.paidup.io/ you will be redirected to https://www.paidup.io/, that means the HTTPS redirection works, but instead of displaying login page, its just show "The page isn't redirecting properly" message.

I already follow the instruction and change my APP_ENV to production.

Any idea how to solve this? My goal is simple, because we already had HTTPS cert so we will use HTTPS instead of HTTP.

Any help will be appreciated!.

Thanks,
Teguh

**Comment by shin1x1** [comment]
Hi, @mtasuandi 
Thank you for using this package and sorry for the delay in response.

I accessed to http://www.paidup.io/ that seems to work well.
Did you resolved it yet ?

**Comment by mtasuandi** [comment]
Hi, @shin1x1 
I think the issue is somewhere in the hosting side. It works well now.

**Comment by shin1x1** [comment]
:+1:
